server:
  port: 8082

spring:
  application:
    name: account-service

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

services:
  persistence:
    url: http://localhost:8080/persistence
