name: CI Pipeline

on:
  push:
    branches:
      - 'feature/**'
  pull_request:
    branches: [ Recette ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
#      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '24'
          cache: maven

      - name: Install dependencies and run tests
        run: ./mvnw clean verify

#      - name: SonarCloud Scan
#        uses: SonarSource/sonarcloud-github-action@v2
#        with:
#          projectBaseDir: .
#        env:
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
